/* THE FREE MARKET GLOBE v2 - admin dashboard */
let ADMIN_DATA=null, charts={};
function money(n){return 'UGX '+Number(n||0).toLocaleString('en-UG')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){let el=document.getElementById('fmgToast');if(!el){el=document.createElement('div');el.id='fmgToast';el.style.cssText='position:fixed;bottom:24px;left:24px;background:#14110F;color:#FBF9F6;padding:12px 18px;border-radius:4px;z-index:500;border-left:4px solid #E8A93B';document.body.appendChild(el)}el.textContent=msg;el.style.opacity='1';clearTimeout(window._t);window._t=setTimeout(()=>el.style.opacity='0',3200)}
async function checkAdminGate(){const s=FMG.getSession();if(s?.type==='admin'){document.getElementById('adminGate').classList.add('hidden');document.getElementById('adminShell').classList.remove('hidden');await bootAdminPanel()}else{document.getElementById('adminGate').classList.remove('hidden');document.getElementById('adminShell').classList.add('hidden')}}
async function attemptAdminLogin(){const err=document.getElementById('gateError');try{await FMG.login(document.getElementById('gateName').value.trim(),document.getElementById('gatePw').value);err.classList.add('hidden');await checkAdminGate()}catch(e){err.textContent=e.message;err.classList.remove('hidden')}}
function openPublicSite(){ const url=new URL('index.html', window.location.href).href; window.open(url,'_blank','noopener'); }
function adminLogout(){FMG.clearSession();checkAdminGate()}
function showAdminSection(id){document.querySelectorAll('.dash-section').forEach(s=>s.classList.add('hidden'));document.getElementById(id)?.classList.remove('hidden');document.querySelectorAll('.dash-nav a[data-section]').forEach(a=>a.classList.toggle('active',a.dataset.section===id));if(id==='sec-traffic')renderTrafficChart();if(id==='sec-progression')renderProgression()}
async function loadAdmin(){ADMIN_DATA=await fmgApi('/admin/overview');return ADMIN_DATA}
async function renderAdminOverview(){const d=await loadAdmin();document.getElementById('kpiUsers').textContent=d.users.length;document.getElementById('kpiBusinesses').textContent=d.businesses.length;document.getElementById('kpiTraffic').textContent=(d.traffic.at(-1)?.[1]||0)+' today';document.getElementById('kpiTrialSlots').textContent=d.trial.remaining+' / '+d.trial.limit+' left'}
function renderUsers(){const b=document.getElementById('usersTableBody');b.innerHTML=ADMIN_DATA.users.length?ADMIN_DATA.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.joined}</td><td><button class="btn btn-danger btn-sm" onclick="deleteUser('${u.id}')">Remove</button></td></tr>`).join(''):'<tr><td colspan="4">No users.</td></tr>'}
async function deleteUser(id){if(!confirm('Remove this user account?'))return;try{await fmgApi('/admin/users/'+id,{method:'DELETE'});await refreshAdmin()}catch(e){toast(e.message)}}
function renderBusinesses(){const b=document.getElementById('businessesTableBody');b.innerHTML=ADMIN_DATA.businesses.length?ADMIN_DATA.businesses.map(x=>{const active=x.freeTrial&&new Date()<=new Date(x.trialEndsAt);return `<tr><td>${esc(x.name)}</td><td>${esc(FMG.categoryById(x.category)?.label||x.category)}</td><td>${esc(FMG.locationById(x.location)?.label||x.location)}</td><td>${x.freeTrial?(active?'Free trial':'Trial ended'):'Paid plan'}</td><td>${x.joined}</td><td><a class="btn btn-outline-dark btn-sm" href="index.html?business=${encodeURIComponent(x.id)}" target="_blank">Public listing</a> <button class="btn btn-danger btn-sm" onclick="deleteBusiness('${x.id}')">Remove</button></td></tr>`}).join(''):'<tr><td colspan="6">No businesses.</td></tr>'}
async function deleteBusiness(id){if(!confirm('Remove this business and all its listings?'))return;try{await fmgApi('/admin/businesses/'+id,{method:'DELETE'});await refreshAdmin()}catch(e){toast(e.message)}}
function renderProducts(){const b=document.getElementById('adminProductsTableBody');b.innerHTML=ADMIN_DATA.products.length?ADMIN_DATA.products.map(p=>{const biz=ADMIN_DATA.businesses.find(x=>x.id===p.bizId);return `<tr><td><img src="${p.image||FMG.placeholder(p.category,p.name)}" style="width:40px;height:40px;object-fit:cover;border-radius:3px"></td><td>${esc(p.name)}</td><td>${esc(biz?.name||'—')}</td><td>${esc(FMG.categoryById(p.category)?.label||p.category)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="btn btn-danger btn-sm" onclick="adminDeleteProduct('${p.id}')">Delete</button></td></tr>`}).join(''):'<tr><td colspan="7">No products.</td></tr>'}
async function adminDeleteProduct(id){if(!confirm('Remove this product from the public site?'))return;try{await fmgApi('/admin/products/'+id,{method:'DELETE'});await refreshAdmin()}catch(e){toast(e.message)}}
function renderTrafficChart(){const ctx=document.getElementById('trafficCanvas');if(!ctx||!ADMIN_DATA)return;if(charts.traffic)charts.traffic.destroy();const arr=ADMIN_DATA.traffic||[];charts.traffic=new Chart(ctx.getContext('2d'),{type:'line',data:{labels:arr.map(x=>x[0].slice(5)),datasets:[{label:'Visits',data:arr.map(x=>x[1]),borderColor:'#1B2A4A',backgroundColor:'rgba(27,42,74,.12)',fill:true}]},options:{plugins:{legend:{display:false}}}})}
function monthKeys(){const a=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);a.push(d.toISOString().slice(0,7))}return a}
function renderProgression(){const keys=monthKeys(),users=ADMIN_DATA.users,biz=ADMIN_DATA.businesses;const uc=keys.map(k=>users.filter(x=>x.joined.slice(0,7)<=k).length),bc=keys.map(k=>biz.filter(x=>x.joined.slice(0,7)<=k).length);if(charts.u)charts.u.destroy();if(charts.b)charts.b.destroy();charts.u=new Chart(document.getElementById('userProgCanvas').getContext('2d'),{type:'line',data:{labels:keys,datasets:[{data:uc,borderColor:'#E8A93B',fill:false}]},options:{plugins:{legend:{display:false}}}});charts.b=new Chart(document.getElementById('bizProgCanvas').getContext('2d'),{type:'bar',data:{labels:keys,datasets:[{data:bc,backgroundColor:'#3B2417'}]},options:{plugins:{legend:{display:false}}}})}
function renderFeedback(){document.getElementById('adminFeedbackList').innerHTML=ADMIN_DATA.feedback.length?ADMIN_DATA.feedback.slice().reverse().map(f=>`<div class="panel" style="margin-bottom:10px;padding:14px"><strong>${esc(f.name)}</strong><span class="badge-chip badge-in" style="margin-left:6px">${esc(f.from)}</span><span style="float:right;color:#6B625B;font-size:.78rem">${new Date(f.createdAt).toLocaleString()}</span><p>${esc(f.message)}</p></div>`).join(''):'<p class="form-note">No feedback.</p>'}
async function renderPaymentSettings(){try{const s=await fmgApi('/admin/settings');document.getElementById('momoAccount').value=s.paymentAccounts?.momo||'';document.getElementById('cardAccount').value=s.paymentAccounts?.mastercard||''}catch(e){toast(e.message)}}
async function savePaymentSettings(){try{await fmgApi('/admin/settings',{method:'PUT',body:JSON.stringify({momo:document.getElementById('momoAccount').value.trim(),mastercard:document.getElementById('cardAccount').value.trim()})});toast('Marketplace payment settings saved.')}catch(e){toast(e.message)}}
function generateReport(){const d=ADMIN_DATA;const revenue=d.orders.reduce((s,o)=>s+Number(o.total||0),0);const text=['THE FREE MARKET GLOBE — Admin report','Generated: '+new Date().toLocaleString(),'','Users: '+d.users.length,'Businesses: '+d.businesses.length,'Products: '+d.products.length,'Orders: '+d.orders.length,'Revenue recorded: '+money(revenue),'Free-trial slots remaining: '+d.trial.remaining].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='free-market-globe-report.txt';a.click()}
async function refreshAdmin(){await renderAdminOverview();renderUsers();renderBusinesses();renderProducts();renderFeedback();renderPaymentSettings()}
async function bootAdminPanel(){await refreshAdmin();document.querySelectorAll('.dash-nav a[data-section]').forEach(a=>a.onclick=e=>{e.preventDefault();showAdminSection(a.dataset.section)});document.getElementById('publicSiteBtn')?.addEventListener('click',openPublicSite);document.getElementById('adminLogoutBtn').onclick=adminLogout;document.getElementById('reportBtn').onclick=generateReport;document.getElementById('paymentSaveBtn').onclick=savePaymentSettings;showAdminSection('sec-overview')}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('gateLoginBtn').onclick=attemptAdminLogin;document.getElementById('gatePw').addEventListener('keydown',e=>{if(e.key==='Enter')attemptAdminLogin()});checkAdminGate()})
