/* THE FREE MARKET GLOBE v2 - business dashboard */
let CURRENT_BIZ=null, DASH=null, selectedLocations=[];
function money(n){return 'UGX '+Number(n||0).toLocaleString('en-UG')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function trialStatus(b){if(!b.freeTrial)return{active:false,label:'Standard subscription',expired:false};const end=new Date(b.trialEndsAt),active=new Date()<=end;return{active,expired:!active,label:active?'Free trial · '+Math.max(0,Math.ceil((end-new Date())/86400000))+' days left':'Free trial ended'}}
async function guardBusinessSession(){const s=FMG.getSession();if(!s||s.type!=='business'){location.href='index.html';return null}try{return(await fmgApi('/business/dashboard')).business}catch{FMG.clearSession();location.href='index.html';return null}}
function showSection(id){document.querySelectorAll('.dash-section').forEach(s=>s.classList.add('hidden'));document.getElementById(id)?.classList.remove('hidden');document.querySelectorAll('.dash-nav a[data-section]').forEach(a=>a.classList.toggle('active',a.dataset.section===id));if(id==='sec-progression')renderChart('progressionCanvas','line');if(id==='sec-sales')renderChart('salesCanvas','bar');if(id==='sec-locations')setTimeout(initMap,50);if(id==='sec-messages')loadBusinessMessages()}
function refreshDash(){return fmgApi('/business/dashboard').then(r=>{DASH=r;CURRENT_BIZ=r.business;renderOverview();renderProductsTable();renderOrdersTable();renderFinance();renderLocationSettings();renderPaymentSettings();renderChatbotSettings();return r})}
function renderOverview(){document.getElementById('bizNameLabel').textContent=CURRENT_BIZ.name;const st=trialStatus(CURRENT_BIZ);document.getElementById('trialPill').textContent=st.label;document.getElementById('trialPill').classList.toggle('expired',st.expired);document.getElementById('kpiRevenue').textContent=money(DASH.revenue);document.getElementById('kpiProducts').textContent=DASH.products.length;document.getElementById('kpiUnits').textContent=DASH.units;document.getElementById('kpiLowStock').textContent=DASH.lowStock;document.getElementById('notificationList').innerHTML=DASH.notifications?.length?DASH.notifications.map(n=>`<li>${esc(n.text)} <span style="color:#6B625B;font-size:.76rem">· ${new Date(n.createdAt).toLocaleString()}</span></li>`).join(''):'<li>No recent notifications.</li>'}
function renderProductsTable(){const body=document.getElementById('productsTableBody');body.innerHTML=DASH.products.length?DASH.products.map(p=>`<tr><td><img src="${p.image||FMG.placeholder(p.category,p.name)}" style="width:44px;height:44px;object-fit:cover;border-radius:3px"></td><td>${esc(p.name)}<br><span style="color:#6B625B;font-size:.78rem">${esc(FMG.categoryById(p.category)?.label||p.category)}</span></td><td>${money(p.price)}${p.discount?` <span style="color:var(--navy)">(-${p.discount}%)</span>`:''}</td><td>${p.stock}</td><td>${p.views||0}</td><td><button class="btn btn-outline-dark btn-sm" onclick="openProductForm('${p.id}')">Edit</button> <button class="btn btn-danger btn-sm" onclick="deleteBizProduct('${p.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="6">No products yet.</td></tr>'}
async function deleteBizProduct(id){if(!confirm('Remove this product from your storefront?'))return;try{await fmgApi('/products/'+id,{method:'DELETE'});await refreshDash();toast('Product removed.')}catch(e){toast(e.message)}}
let editingProductId=null,pendingImage=null;
function renderProductDeliverySettings(saved={}){const el=document.getElementById('productDeliverySettings');el.innerHTML=FMG.locations.map(l=>{const v=saved[l.id]||{};return `<div class="location-setting-row"><label><input type="checkbox" data-pdl="${l.id}" ${v.enabled?'checked':''}> ${l.label}</label><input type="number" min="0" max="10000" step="100" data-pdf="${l.id}" value="${Number(v.fee||0)}" placeholder="Fee UGX"></div>`}).join('')}
function collectProductDeliverySettings(){const o={};FMG.locations.forEach(l=>{const enabled=document.querySelector(`[data-pdl="${l.id}"]`)?.checked;const fee=Math.min(10000,Math.max(0,Number(document.querySelector(`[data-pdf="${l.id}"]`)?.value||0)));if(enabled)o[l.id]={enabled:true,fee}});return o}
function openProductForm(id){editingProductId=id||null;pendingImage=null;const p=id?DASH.products.find(x=>x.id===id):null;document.getElementById('productFormTitle').textContent=p?'Edit product':'Upload product';document.getElementById('pfName').value=p?.name||'';document.getElementById('pfCategory').value=p?.category||FMG.categories[0].id;document.getElementById('pfPrice').value=p?.price||'';document.getElementById('pfDiscount').value=p?.discount||0;document.getElementById('pfStock').value=p?.stock??'';document.getElementById('pfDesc').value=p?.desc||'';document.getElementById('uploadPreview').src=p?.image||FMG.placeholder(FMG.categories[0].id,'New');renderProductDeliverySettings(p?.deliveryOptions||{});document.getElementById('productFormError').classList.add('hidden');document.getElementById('productFormOverlay').classList.remove('hidden')}
function closeProductForm(){document.getElementById('productFormOverlay').classList.add('hidden');pendingImage=null}
function handleImageSelect(input){const file=input.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const max=1200;let w=img.width,h=img.height;if(Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);c.toBlob(blob=>{pendingImage=blob;document.getElementById('uploadPreview').src=URL.createObjectURL(blob)},'image/webp',.78)};img.src=e.target.result};reader.readAsDataURL(file)}
async function saveProductForm(){const err=document.getElementById('productFormError');const name=document.getElementById('pfName').value.trim(),price=Number(document.getElementById('pfPrice').value),stock=Number(document.getElementById('pfStock').value);if(!name||price<=0||stock<0||!Number.isFinite(stock)){err.textContent='Enter a product name, positive price and valid stock quantity.';err.classList.remove('hidden');return}err.classList.add('hidden');const fd=new FormData();fd.append('name',name);fd.append('category',document.getElementById('pfCategory').value);fd.append('price',price);fd.append('discount',Math.min(90,Math.max(0,Number(document.getElementById('pfDiscount').value)||0)));fd.append('stock',Math.floor(stock));fd.append('desc',document.getElementById('pfDesc').value.trim());fd.append('deliveryOptions',JSON.stringify(collectProductDeliverySettings()));if(pendingImage)fd.append('image',pendingImage,'product.webp');try{await fmgApi(editingProductId?'/products/'+editingProductId:'/products',{method:editingProductId?'PUT':'POST',body:fd});closeProductForm();await refreshDash();toast(editingProductId?'Product updated and live on the public site.':'Product uploaded to the server and is now live on the public site.')}catch(e){err.textContent=e.message;err.classList.remove('hidden')}}
function renderOrdersTable(){const body=document.getElementById('ordersTableBody');const lines=DASH.lines||[];body.innerHTML=lines.length?lines.slice().reverse().map(l=>`<tr><td>${new Date(l.date).toLocaleDateString()}</td><td>${esc(DASH.products.find(p=>p.id===l.productId)?.name||l.productId)}</td><td>${l.qty}</td><td>${esc(FMG.locationById(l.location)?.label||l.location||'')}</td><td>${money(l.lineTotal)}</td></tr>`).join(''):'<tr><td colspan="5">No sales yet.</td></tr>'}
function renderFinance(){const revenue=DASH.revenue||0,cogs=Math.round(revenue*.6),gross=revenue-cogs,st=trialStatus(CURRENT_BIZ),fee=st.active?0:Math.round(revenue*.05),net=gross-fee,inventory=DASH.products.reduce((s,p)=>s+p.price*p.stock,0),assets=inventory+revenue;document.getElementById('incomeStatement').innerHTML=`<table class="data-table"><tr><td>Sales revenue</td><td style="text-align:right">${money(revenue)}</td></tr><tr><td>Estimated cost of goods</td><td style="text-align:right">(${money(cogs)})</td></tr><tr><th>Gross profit</th><th style="text-align:right">${money(gross)}</th></tr><tr><td>Platform fee</td><td style="text-align:right">(${money(fee)})</td></tr><tr><th>Net profit</th><th style="text-align:right">${money(net)}</th></tr></table>`;document.getElementById('balanceSheet').innerHTML=`<table class="data-table"><tr><td>Cash from sales</td><td style="text-align:right">${money(revenue)}</td></tr><tr><td>Inventory</td><td style="text-align:right">${money(inventory)}</td></tr><tr><th>Total assets</th><th style="text-align:right">${money(assets)}</th></tr><tr><th>Owner equity</th><th style="text-align:right">${money(assets)}</th></tr></table>`}
function renderLocationSettings(){const saved=CURRENT_BIZ.deliveryLocations||{};document.getElementById('locationSettingsList').innerHTML=FMG.locations.map(l=>{const v=saved[l.id]||{};return `<div class="location-setting-row"><label><input type="checkbox" data-bizloc="${l.id}" ${v.enabled?'checked':''}> ${l.label}</label><input type="number" min="0" max="10000" step="100" data-bizfee="${l.id}" value="${Number(v.fee||0)}" placeholder="Delivery fee UGX"></div>`}).join('');selectedLocations=FMG.locations.filter(l=>saved[l.id]?.enabled).map(l=>l.id);renderLocationChips()}
function renderLocationChips(){document.getElementById('locationChips').innerHTML=selectedLocations.map(id=>`<span class="location-chip selected">${FMG.locationById(id)?.label}</span>`).join('')||'<span class="form-note">No delivery points enabled yet.</span>'}
async function saveBusinessLocations(){const o={};FMG.locations.forEach(l=>{const enabled=document.querySelector(`[data-bizloc="${l.id}"]`)?.checked;const fee=Math.min(10000,Math.max(0,Number(document.querySelector(`[data-bizfee="${l.id}"]`)?.value||0)));if(enabled)o[l.id]={enabled:true,fee}});try{const r=await fmgApi('/business/settings',{method:'PUT',body:JSON.stringify({deliveryLocations:o})});CURRENT_BIZ=r.business;toast('Delivery points and fees saved. Maximum fee is UGX 10,000.');renderLocationSettings();initMap()}catch(e){toast(e.message)}}
let bizMap=null;function initMap(){if(typeof L==='undefined')return;const el=document.getElementById('map');if(!el)return;if(bizMap)bizMap.remove();bizMap=L.map(el).setView([0,31.9],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:17}).addTo(bizMap);FMG.locations.forEach(l=>{const on=CURRENT_BIZ.deliveryLocations?.[l.id]?.enabled;L.circleMarker([l.lat,l.lng],{radius:on?9:5,color:on?'#E8A93B':'#1B2A4A',fillColor:on?'#E8A93B':'#1B2A4A',fillOpacity:.85}).addTo(bizMap).bindPopup(`${l.label}${on?' — enabled':''}`)})}
function renderPaymentSettings(){const p=CURRENT_BIZ.paymentMethods||{};document.getElementById('payMomoEnabled').checked=!!p.momo?.enabled;document.getElementById('payMomoAccount').value=p.momo?.account||'';document.getElementById('payAirtelEnabled').checked=!!p.airtel?.enabled;document.getElementById('payAirtelAccount').value=p.airtel?.account||'';document.getElementById('payCardEnabled').checked=!!p.mastercard?.enabled;document.getElementById('payCardAccount').value=p.mastercard?.account||''}
async function savePaymentMethods(){const paymentMethods={momo:{enabled:document.getElementById('payMomoEnabled').checked,account:document.getElementById('payMomoAccount').value.trim()},airtel:{enabled:document.getElementById('payAirtelEnabled').checked,account:document.getElementById('payAirtelAccount').value.trim()},mastercard:{enabled:document.getElementById('payCardEnabled').checked,account:document.getElementById('payCardAccount').value.trim()}};for(const [k,v] of Object.entries(paymentMethods))if(v.enabled&&!v.account)return toast(`Enter the ${k==='momo'?'MTN MoMo':k==='airtel'?'Airtel Pay':'Mastercard'} account details.`);try{const r=await fmgApi('/business/settings',{method:'PUT',body:JSON.stringify({paymentMethods})});CURRENT_BIZ=r.business;renderPaymentSettings();toast('Payment methods saved. Customers will now see the enabled options.')}catch(e){toast(e.message)}}
function renderChatbotSettings(){const c=CURRENT_BIZ.chatbot||{};document.getElementById('chatbotPersona').value=c.persona||'friendly';document.getElementById('chatbotGreeting').value=c.greeting||`Hi! Thanks for visiting ${CURRENT_BIZ.name}. How can I help?`}
async function saveChatbotSettings(){try{const r=await fmgApi('/business/settings',{method:'PUT',body:JSON.stringify({chatbot:{persona:document.getElementById('chatbotPersona').value,greeting:document.getElementById('chatbotGreeting').value.trim()}})});CURRENT_BIZ=r.business;toast('Assistant settings saved.')}catch(e){toast(e.message)}}
async function loadBusinessMessages(){const box=document.getElementById('messagesList');try{const r=await fmgApi('/messages/'+CURRENT_BIZ.id);const groups={};r.messages.forEach(m=>(groups[m.userId]??=[]).push(m));box.innerHTML=Object.keys(groups).length?Object.entries(groups).map(([uid,msgs])=>`<div class="panel" style="margin-bottom:12px;padding:14px"><strong>Customer ${esc(uid)}</strong><div style="max-height:180px;overflow:auto;margin:8px 0">${msgs.map(m=>`<div style="padding:7px;background:${m.from==='business'?'#F0ECE7':'#FFF6DF'};margin:5px 0"><strong>${m.from==='business'?'Business':'Customer'}:</strong> ${esc(m.text)}<small style="display:block;color:#6B625B">${new Date(m.createdAt).toLocaleString()}</small></div>`).join('')}</div><div class="field"><input id="reply_${uid}" placeholder="Reply to this customer"></div><button class="btn btn-primary btn-sm" onclick="replyToCustomer('${uid}')">Send reply</button></div>`).join(''):'<p class="form-note">No direct customer messages yet.</p>'}catch(e){toast(e.message)}}
async function replyToCustomer(userId){const input=document.getElementById('reply_'+userId),text=input.value.trim();if(!text)return;try{await fmgApi('/messages/'+CURRENT_BIZ.id+'/reply',{method:'POST',body:JSON.stringify({userId,text})});input.value='';await loadBusinessMessages();toast('Reply delivered to the customer.')}catch(e){toast(e.message)}}
let chartCache={};function renderChart(canvasId,type){const c=document.getElementById(canvasId);if(!c||typeof Chart==='undefined')return;const lines=DASH.lines||[],months={};for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);months[d.toISOString().slice(0,7)]=0}lines.forEach(l=>{const k=l.date.slice(0,7);if(k in months)months[k]+=l.lineTotal});if(chartCache[canvasId])chartCache[canvasId].destroy();chartCache[canvasId]=new Chart(c.getContext('2d'),{type,data:{labels:Object.keys(months),datasets:[{label:'Sales (UGX)',data:Object.values(months),borderColor:'#E8A93B',backgroundColor:'#3B2417',fill:type==='line',tension:.25}]},options:{plugins:{legend:{display:false}}}})}
function logout(){FMG.clearSession();location.href='index.html'}
document.addEventListener('DOMContentLoaded',async()=>{CURRENT_BIZ=await guardBusinessSession();if(!CURRENT_BIZ)return;try{DASH=await refreshDash()}catch(e){toast(e.message)};document.querySelectorAll('.dash-nav a[data-section]').forEach(a=>a.onclick=e=>{e.preventDefault();showSection(a.dataset.section)});document.getElementById('publicSiteBtn')?.addEventListener('click',openPublicSite);document.getElementById('logoutBtn').onclick=logout;document.getElementById('addProductBtn').onclick=()=>openProductForm();document.getElementById('productFormClose').onclick=closeProductForm;document.getElementById('productFormSave').onclick=saveProductForm;document.getElementById('imageInput').onchange=e=>handleImageSelect(e.target);document.getElementById('chatbotSaveBtn').onclick=saveChatbotSettings;document.getElementById('paymentMethodsSaveBtn').onclick=savePaymentMethods;document.getElementById('locationSettingsList').addEventListener('change',()=>renderLocationChips());document.getElementById('sec-locations').insertAdjacentHTML('afterbegin','<div style="margin-bottom:14px"><button class="btn btn-primary btn-sm" id="saveLocationSettingsBtn">Save delivery points and fees</button></div>');document.getElementById('saveLocationSettingsBtn').onclick=saveBusinessLocations;showSection('sec-overview')});
